---
# tasks file for python
- name: Install dependencies
  apt: name={{ item }} state=present
  with_items:
    - python
    - python-setuptools
    - python-dev
    - build-essential
    - python3-pip
    - python3-mysqldb